language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install
  - polymer install
before_script:
  - npm run validate-branch
script:
  - npm run build
branches:
  only:
    - "master"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/sopra-quiz-app
  github_token: $GITHUBTOKEN # Set in travis-ci.org dashboard
  on:
    branch: master